- src/Common/Configuration.ts
#4 Added Azure connection string
> Added Azure connection string

- .gitignore
- src/Common/Configuration.ts
- src/app.ts
- src/hazzat-api-ppe - Web Deploy.pubxml
- src/hazzat-api.njsproj
- src/package-lock.json
- src/package.json
- src/tsconfig.json
- Built code into src/dist folder
- Added a ppe app plan and web app
- fixed build errors from typescript upgrade
> Built code into src/dist folder

- src/package-lock.json
- src/package.json
- src/tsconfig.json
- test/init.spec.ts
> New Release from Develop

- src/app.ts
> Generalize URI path to Routes

- src/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/ISeasonInfo.ts
- src/Routes/SeasonsController.ts
- src/test/seasons.spec.ts
- Updated seasons schema to include id and reason name.
- Updated single season to return same schema as list of seasons
- Updated tests and swagger
> Updated seasons schema

- azure-pipelines.yml
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- Made connection pool static
- Switched to Azure SQL db
> Made connection pool static

- src/Common/Types/FormatType.ts
- src/Common/Types/StringMap.ts
- src/DataProviders/IDataProvider.ts
- src/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/IServiceInfo.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/package.json
- src/test/seasons.spec.ts
Added API route for Season services
> Added API route for Season services

- src/package-lock.json
- src/package.json
> Updated mssql

- src/package-lock.json
- src/package.json
> Updated all packates

- src/Common/Utils/Logger.ts
- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/hazzat-api.njsproj
- Made Sql pool a singleton
- Lazily initialized connection pool on first load
- Added logger class
- Added additional logging and exception handling
> fix sql connection

- src/DataProviders/IDataProvider.ts
- src/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/IServiceHymnInfo.ts
- src/Routes/SeasonsController.ts
- src/Routes/ServicesController.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/test/services.spec.ts
- Added Services controller
- Added tests
- Added Service Hymn interfaces
- Added Services route
> Added services controller

- src/Common/Utils/Logger.ts
- src/Routes/BaseController.ts
- src/app.ts
- src/package-lock.json
- src/package.json
replaced console.logging with winston
> Added winston logging

- azure-pipelines.ppe.gated.yml
- azure-pipelines.ppe.yml
- azure-pipelines.prod.yml
- src/DataProviders/IDataProvider.ts
- src/DataProviders/SqlDataProvider/Scripts/00.00.02.Install.sql
- src/DataProviders/SqlDataProvider/Scripts/00.00.02.Uninstall.sql
- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/ISeasonInfo.ts
- src/Models/IServiceInfo.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/seasons.spec.ts
Added seasons/[seasonId]/services/[serviceId] route
Added unit tests
Updated Seasons object to remove reason id/name
Updated Services object to remove content counts
Updated unit tests
> Added seasons/seasonId/services/serviceId route

- src/package-lock.json
- src/package.json
This reverts commit 0ff85f81276f30d22bde00ef3ae6baf47757e4a2.
> Revert "Bump @types/node from 14.0.10 to 14.0.11 in /src (#231)"

- src/Common/Errors.ts
- src/DataProviders/IDataProvider.ts
- src/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/DataProviders/SqlDataProvider/Scripts/00.00.04.Install.sql
- src/DataProviders/SqlDataProvider/Scripts/00.00.04.Uninstall.sql
- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/IServiceHymnFormatContentInfo.ts
- src/Models/IServiceHymnFormatInfo.ts
- src/Routes/BaseController.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/Helpers/Validators.ts
- src/test/seasons.spec.ts
Implementation for format contents API
*Note:*
- Build Validation will fail till schema is updated
- Audio and Musical formats are not supported yet since DB currently only contains file references from DNN
> Added Contents route & handler

- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/IVariationInfo.ts
- src/Routes/SeasonsController.ts
- src/test/Helpers/Validators.ts
- src/test/seasons.spec.ts
Converted db text to array of paragraphs
> Converted db text to array of paragraphs

- src/DataProviders/SqlDataProvider/SqlConstants.ts
- src/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Models/IVariationInfo.ts
- src/Routes/SeasonsController.ts
- src/test/Helpers/Validators.ts
- src/test/seasons.spec.ts
> Collated text into columns

- src/package-lock.json
- src/package.json
Intalling diagnostic package to fix runtime errors
> Intalling diagnostic package to fix runtime errors

- src/package-lock.json
- src/package.json
This reverts commit dc513c933a6ebd9f6f691e9e596b50fa746cbcfb.
> Revert "Bump swagger-jsdoc from 4.0.0 to 5.0.1 in /src (#319)"

- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.06.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.06.Uninstall.sql
- src/hazzat-api.njsproj
Updated procedures to add schema
> Updated procedures to add schema

- src/Models/IVariationInfo.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.07.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.07.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/Helpers/Validators.ts
- src/test/seasons.spec.ts
Updated SQL SP
Added Audio Format
Updated api swagger
> Added Audio Format

- deployments/Azure/appservice_parameters.json
- deployments/Azure/appservice_template.json
- deployments/Azure/blobstorage_parameters.json
- deployments/Azure/blobstorage_template.json
- deployments/Azure/keyvault_parameters.json
- deployments/Azure/keyvault_template.json
- deployments/Azure/sqldb_parameters.json
- deployments/Azure/sqldb_template.json
- developer/start-environment.ps1
Added Azure deployment templates
Updated dev scripts
> Azure Deployment templates

- src/package-lock.json
- src/package.json
This reverts commit 340e30cc1a5949f5d5047cb1fec30cd3abbdab41.
> Revert "Bump swagger-jsdoc from 4.0.0 to 6.0.2 in /src"

- azure-pipelines.dev.yml
Updated artifact name for dev pipeline
> Updated artifact name

- azure-pipelines.dev.yml
- azure-pipelines.ppe.gated.yml
- azure-pipelines.ppe.yml
- azure-pipelines.prod.yml
Update Azure pipelines Agent pool to VS2019
> Update Azure pipelines Agent pool to VS2019

- azure-pipelines.dev.yml
- azure-pipelines.ppe.gated.yml
- azure-pipelines.ppe.yml
- azure-pipelines.prod.yml
- src/package-lock.json
- src/package.json
Installed mocha trx reporter
Updated mocha to use trx reporter
Modified azure pipelines to publish test results file
> Publish test results for Azure Pipelines

- .gitignore
- src/Models/IVariationInfo.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.08.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.08.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/Helpers/Validators.ts
- src/test/seasons.spec.ts
Added Musical Notes support
Added types
Updated swagger
Updated tests
Updates SQL
> Added Musical Notes

- src/Models/ITuneInfo.ts
- src/Models/ITypeInfo.ts
- src/Providers/DataProviders/IDataProvider.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.09.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.09.Uninstall.sql
- src/Providers/DataProviders/SqlDataProvider/SqlConstants.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/ResourceTypes.ts
- src/Routes/TunesController.ts
- src/Routes/TypesController.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/test/Helpers/Validators.ts
- src/test/tunes.spec.ts
- src/test/types.spec.ts
Added Controllers
Added SQL upgrade & downgrade scripts
Added Data provider methods
Added Service provider methods
Added Unit tests
> Added Tunes & Types controller

- src/Common/Utils/AsyncDelayer.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/package-lock.json
- src/package.json
- src/test/E2ETests/ApiValidator.ts
- src/test/E2ETests/TestConfiguration.ts
- src/test/E2ETests/dev.json
- src/test/E2ETests/local.json
- src/test/E2ETests/ppe.json
- src/test/E2ETests/prod.json
- src/test/E2ETests/seasons.spec.ts
- src/test/E2ETests/tunes.spec.ts
- src/test/E2ETests/types.spec.ts
- src/test/Helpers/Validators.ts
- src/test/IntegrationTests/seasons.spec.ts
- src/test/IntegrationTests/tunes.spec.ts
- src/test/IntegrationTests/types.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
- src/test/UnitTests/tunesServiceProvider.spec.ts
- src/test/UnitTests/typesServiceProvider.spec.ts
Added E2E tests
Added test configurations for local, dev, ppe, and prod
Added API validator class using builder style
Fixed sql connection pool error when state is "connecting"
Updated validators to work with chai and axios responses
Fixed erroneous Integration tests
Added AsyncDelayer util
> Implementing E2E tests

- src/Common/Utils/AsyncDelayer.ts
- src/Common/Utils/IRetryPolicy.ts
- src/Common/Utils/OperationExecutor.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/hazzat-api.njsproj
- src/package.json
- src/test/E2ETests/TestConfiguration.ts
- src/test/E2ETests/seasons.spec.ts
- src/test/E2ETests/tunes.spec.ts
- src/test/E2ETests/types.spec.ts
- src/test/UnitTests/operationExecutor.spec.ts
Added an async operator executor with a retry policy.
Updated E2E tests to use retry policy to wake up service
> Adding operator executor with retry policy

- src/Common/Utils/OperationExecutor.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/test/E2ETests/seasons.spec.ts
- src/test/E2ETests/tunes.spec.ts
- src/test/E2ETests/types.spec.ts
- src/test/UnitTests/operationExecutor.spec.ts
Using retry policy for connection pool
> Using retry policy for connection pool

- azure-pipelines.dev.yml
- azure-pipelines.ppe.gated.yml
- azure-pipelines.ppe.yml
- azure-pipelines.prod.yml
- src/Common/Utils/OperationExecutor.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
> Fixed connecting condition

- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
Added logging to SQL connection
> Added logging

- .build/createDeploymentArchive.ps1
- .pipelines/azure-pipelines.dev.yml
- .pipelines/azure-pipelines.ppe.gated.yml
- .pipelines/azure-pipelines.ppe.yml
- .pipelines/azure-pipelines.prod.yml
- azure-pipelines.dev.yml
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
Migrated hosting plan to linux
Migrating pipelines to linux
Moved pipelines to folder
Removed retries for SQL connection pool
> Migrating app service to linux

- src/Providers/DataProviders/IDataProvider.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.12.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.12.Uninstall.sql
- src/Providers/DataProviders/SqlDataProvider/SqlConstants.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/TunesController.ts
- src/Routes/TypesController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/tunes.spec.ts
- src/test/E2ETests/types.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/Helpers/Validators.ts
- src/test/IntegrationTests/tunes.spec.ts
- src/test/IntegrationTests/types.spec.ts
- src/test/UnitTests/tunesServiceProvider.spec.ts
- src/test/UnitTests/typesServiceProvider.spec.ts
Added Formats route to Tunes/Types
Added Unit tests
Added Integration tests
Added E2E tests
> Added Format route to tunes/types controllers

- src/Providers/DataProviders/IDataProvider.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.13.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.13.Uninstall.sql
- src/Providers/DataProviders/SqlDataProvider/SqlConstants.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/TunesController.ts
- src/Routes/TypesController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/seasons.spec.ts
- src/test/E2ETests/tunes.spec.ts
- src/test/E2ETests/types.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/Helpers/Validators.ts
- src/test/IntegrationTests/tunes.spec.ts
- src/test/IntegrationTests/types.spec.ts
- src/test/UnitTests/tunesServiceProvider.spec.ts
- src/test/UnitTests/typesServiceProvider.spec.ts
- Added variations route
- Added Unit Tests
- Added Integration Tests
- Added E2E tests
> Added Variations route to Types/Tunes controllers

- src/Models/IBookletInfo.ts
- src/Providers/DataProviders/IDataProvider.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.14.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.14.Uninstall.sql
- src/Providers/DataProviders/SqlDataProvider/SqlConstants.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/BookletsController.ts
- src/Routes/ResourceTypes.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/booklets.spec.ts
- src/test/E2ETests/seasons.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/Helpers/Validators.ts
- src/test/IntegrationTests/booklets.spec.ts
- src/test/UnitTests/bookletsServiceProvider.spec.ts
- Added Booklets controller
- Added routes and resource types
- Added SQL scripts
- Added Unit tests
- Added Integration Tests
- Added E2E tests
> Added Booklets Controller

- src/Models/IBookletInfo.ts
- src/Providers/DataProviders/IDataProvider.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.14.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.14.Uninstall.sql
- src/Providers/DataProviders/SqlDataProvider/SqlConstants.ts
- src/Providers/DataProviders/SqlDataProvider/SqlDataProvider.ts
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/BookletsController.ts
- src/Routes/ResourceTypes.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/package-lock.json
- src/package.json
- src/test/E2ETests/booklets.spec.ts
- src/test/E2ETests/seasons.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/Helpers/Validators.ts
- src/test/IntegrationTests/booklets.spec.ts
- src/test/UnitTests/bookletsServiceProvider.spec.ts
> Developer to master

- .pipelines/azure-pipelines.dev.yml
- .pipelines/azure-pipelines.ppe.gated.yml
- .pipelines/azure-pipelines.ppe.yml
- .pipelines/azure-pipelines.prod.yml
- src/app.ts
- src/package-lock.json
- src/package.json
> Developer snap to master

- src/Common/Configuration.ts
- src/Common/Types/ContentLanguage.ts
- src/Common/Types/ServiceLanguage.ts
- src/Common/Utils/LanguageHelpers.ts
- src/Models/IVariationInfo.ts
- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.15.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.15.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
- src/test/UnitTests/tunesServiceProvider.spec.ts
- src/test/UnitTests/typesServiceProvider.spec.ts
- Added support for Accept-Language header
- Localized Seasons
- Updated tests
> Localization Support

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.16.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.16.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
Localization support for services
> Localization support for services

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.16.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.16.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
* Localization support for services
* Fixed spacing
Co-authored-by: Fady Wahba <fadyw@microsoft.com>
> Localization support for services (#679)

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.17.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.17.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
Added localization support for Service Hymns
> Added localization support for Service Hymns

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.18.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.18.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
Enable localization support for Formats
> Enable localization support for Formats

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.18.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.18.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/SeasonsController.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/seasonsServiceProvider.spec.ts
Co-authored-by: Fady Wahba <fadyw@microsoft.com>
> Enable localization support for Formats (#687)

- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.20.Install.sql
Fixed SQL script to be not nullable
> Fixed SQL script

- src/Providers/DataProviders/SqlDataProvider/HazzatDbSchema.ts
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.21.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.21.Uninstall.sql
- src/Providers/ServiceProviders/Helpers/HazzatContentUtils.ts
- src/Providers/ServiceProviders/HymnsServiceProvider.ts
- src/Providers/ServiceProviders/IHymnsServiceProvider.ts
- src/Routes/BookletsController.ts
- src/Routes/SeasonsController.ts
- src/Routes/TunesController.ts
- src/Routes/TypesController.ts
- src/app.ts
- src/hazzat-api.njsproj
- src/test/E2ETests/localization.spec.ts
- src/test/Helpers/SqlDataProviderMock.ts
- src/test/IntegrationTests/localization.spec.ts
- src/test/UnitTests/bookletsServiceProvider.spec.ts
> localize booklets

- src/Routes/BookletsController.ts
- src/Routes/SeasonsController.ts
- src/Routes/TunesController.ts
- src/Routes/TypesController.ts
> Fixed swagger docs

- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.23.Install.sql
- src/Providers/DataProviders/SqlDataProvider/Scripts/00.00.23.Uninstall.sql
- src/hazzat-api.njsproj
Fixed seasons list to show only the ones that have services
> Fixed seasons List
